### ISSUE TITLE
vehicle logo detect !!

### ISSUE THREAD

**Issue by richardminh** [kcg2015/Vehicle-Detection-and-Tracking#10]
Dear, Mr Kcg2015, How are you?
Your project is very helpful and explanation is very detail so thanks for your efforts for developing this project. 
By the way, Did you have experiences in vehicle logo detection with YOLO?
I am new about training with YOLO so that I wanna receive your kindly help.

Thanks and Regards, RIchardMinh.

**Comment by kcg2015** [comment]
Thanks for the kind words.  I have not done any logo detection. Also, I don't have too much experience with YOLO model.  My only suggestion now it to find some good YOLO repos and follow their steps to train from scratch, assuming you already have enough training samples and labels. Hope this would help.

**Comment by richardminh** [comment]
Thanks for your kind reply. I will do..

**Comment by kcg2015** [comment]
Let me close this issue for now.
