### ISSUE TITLE
where is 'vis_util'?

### ISSUE THREAD

**Issue by songjd** [kcg2015/Vehicle-Detection-and-Tracking#11]
I can't find the 'vis_util' in the file `detector.py`.

**Comment by kcg2015** [comment]
You need to uncomment the following two lines of the code:
#os.chdir(cwd+'/models')
#from object_detection.utils import visualization_utils as vis_util

Basically you need to import object_detection.utils to use visualization_utils.

Let me know this would help.

**Comment by kcg2015** [comment]
Let me close this issue for now.
