### ISSUE TITLE
Getting an error when executing main.py with videos

### ISSUE THREAD

**Issue by anzy0621** [kcg2015/Vehicle-Detection-and-Tracking#12]
Hello,
           Thank you for this amazing tutorial! I really appreciate it! I was trying to execute your code with videos and I'm getting this particular error
In line 43 of main.py
   in assign_detections_to_trackers
    IOU_mat[t,d] = box_iou2(trk,det)
NameError: name 'box_iou2' is not defined

**Comment by kcg2015** [comment]
Hi, @anzy0621 
Please change line 13 to from helper import *
or line 42 to IOU_mat[t, d] =helper.box_iou2(trk, det) to see if the code would run. Let me know.

Best,

Kyle

**Comment by zhangyuan1997** [comment]
> Hi, @anzy0621
> Please change line 13 to from helper import *
> or line 42 to IOU_mat[t, d] =helper.box_iou2(trk, det) to see if the code would run. Let me know.
> 
> Best,
> 
> Kyle

I also meet this problem and i have solved it by your method. Thanks a lot.

**Comment by anzy0621** [comment]
It worked, thank you!
