### ISSUE TITLE
Error occur when using my own video

### ISSUE THREAD

**Issue by zhangyuan1997** [kcg2015/Vehicle-Detection-and-Tracking#14]
Dear, Mr Kcg2015, How are you?
Your project is very helpful and explanation is very detail so thanks for your efforts for developing this project.
When I run main.py to test my own video, there is something wrong.(video information as follows, test file size about 1.5GB)

![qq 20190130193440](https://user-images.githubusercontent.com/30192850/51978857-6352b500-24c6-11e9-99c2-a295afeb2efc.png)

When the first frame is detected, the program terminates. The results and errors of the first frame detection are as follows:

![qq 20190130193615](https://user-images.githubusercontent.com/30192850/51979118-3c48b300-24c7-11e9-9ee3-fbbc8f369c0d.png)
![qq 20190130193628](https://user-images.githubusercontent.com/30192850/51979122-410d6700-24c7-11e9-8a11-1c36280cea70.png)

I would like to ask why there is such a mistake, thank you for your solution.

                                                                                                                                                                 Best.

**Comment by kcg2015** [comment]
@zhangyuan1997, thanks a lot for bringing this up.  It could well be a bug. I will look into it.  Meanwhile, could you try commenting out the line 147 to see if it works? Alternatively  you can  add if len(track_id_list) > 0: tmp_trk.id = track_id_lst.popleft() to avoid popping an empty list.

**Comment by zhangyuan1997** [comment]
> @zhangyuan1997, thanks a lot for bringing this up. It could well be a bug. I will look into it. Meanwhile, could you try commenting out the line 147 to see if it works? Alternatively you can add if len(track_id_list) > 0: tmp_trk.id = track_id_lst.popleft() to avoid popping an empty list.

Thanks a lot.I will try to debug  with your method. The same error occurred (pop from an empty deque) when I used other video to test, but it happened at 198th frame.
![qq 20190131102951](https://user-images.githubusercontent.com/30192850/52026556-3bedfd80-2543-11e9-9cb3-72211308ba1f.png)
Thanks a lot for your response. Have a good day!
Best Yuan.

**Comment by zhangyuan1997** [comment]
> @zhangyuan1997, thanks a lot for bringing this up. It could well be a bug. I will look into it. Meanwhile, could you try commenting out the line 147 to see if it works? Alternatively you can add if len(track_id_list) > 0: tmp_trk.id = track_id_lst.popleft() to avoid popping an empty list.

Thank you very much! When I comment out the line 147, it works with no error.

**Comment by zhangyuan1997** [comment]
> @zhangyuan1997, thanks a lot for bringing this up. It could well be a bug. I will look into it. Meanwhile, could you try commenting out the line 147 to see if it works? Alternatively you can add if len(track_id_list) > 0: tmp_trk.id = track_id_lst.popleft() to avoid popping an empty list.

I wonder why there is an empty deque?

**Comment by kcg2015** [comment]
@zhangyuan1997 I am wondering about this too. I have not encountered this situation before.

**Comment by zhangyuan1997** [comment]
> @zhangyuan1997 I am wondering about this too. I have not encountered this situation before.

Have you tried multiple different datasets before, including the ones you recorded?If you need the data set I recorded to help solve the bug, I will send it to you by email.

**Comment by zhangyuan1997** [comment]
Sorry to take up your time, how can I draw confidence label on each bounding box.
Thanks a lot for your reply.

**Comment by kcg2015** [comment]
@zhangyuan1997, I am lookining into my code and would let you know if I fix the bug. Thanks again.

**Comment by kcg2015** [comment]
You can modify
def draw_box_label(img, bbox_cv2, box_color=(0, 255, 255), show_label=True):
in helper.py

Best

**Comment by zhangyuan1997** [comment]
Thanks a lot. I have added this label😄

**Comment by zhangyuan1997** [comment]
> You can modify def draw_box_label(img, bbox_cv2, box_color=(0, 255, 255), show_label=True): in helper.py Best
> […](#)

Hello, sorry to take up your time. I would like to ask the score in the scores obtained from this statement (line53: self.scores =self.detection_graph.get_tensor_by_name('detection_scores:0')) in the detector.py defaults to the highest score for each box? I found that each box corresponds to a score, corresponding to a category. The figure below shows 100 boxes, 100 categories, and 100 predicted scores (where the red line is drawn) in the first frame. 
![qq 20190201171327](https://user-images.githubusercontent.com/30192850/52113945-b141f700-2645-11e9-97ba-be212c55157b.png)
But in a general classification task should not be a box corresponding to multiple predicted categories and scores? Rather than the 1:1:1 relationship above.

**Comment by zhangyuan1997** [comment]
In addition, what is the basis for the score threshold to be 0.3?
![qq 20190201172319](https://user-images.githubusercontent.com/30192850/52114135-36c5a700-2646-11e9-8014-d2af12e02523.png)

Thanks a lot for your response!
Best.

**Comment by zhangyuan1997** [comment]
> In addition,  why is the basis for the score threshold to be 0.3?
> ![qq 20190201172319](https://user-images.githubusercontent.com/30192850/52114135-36c5a700-2646-11e9-8014-d2af12e02523.png)
> 
> Thanks a lot for your response!
> Best.

**Comment by kcg2015** [comment]
@zhangyuan1997,  you have to tune this parameter based on the detector's performance on your images. If the value is too low, you would have false-positives. If the value is too high, you would have miss-detections. I choose 0.3 because it works the best for the images I tested.

**Comment by zhangyuan1997** [comment]
Thanks a lot！Having a discussion with you has taught me a lot.😊😊😊Thank you very much. Happy New Year.

**Comment by kcg2015** [comment]
Glad that I can be of some help. Let me close this issue for now.
