### ISSUE TITLE
name 'CarDetector' is not defined

### ISSUE THREAD

**Issue by SignalImageCV** [kcg2015/Vehicle-Detection-and-Tracking#2]
hi, I don't know why I got this wrong message?
$ python main.py
Traceback (most recent call last):
  File "main.py", line 193, in <module>
    det = CarDetector()
NameError: name 'CarDetector' is not defined

**Comment by kcg2015** [comment]
@SignalImageCV , let me look into this.  Meanwhile, if you use Spyder IDE, you can try to run helpers.py, detector.py, and tracker.py first. Then run main.py again, see if you still get this error message.  Let me know.

Best,
Kyle

**Comment by maearnie** [comment]
Hi I also got the same error. I run helpers.py, detector.py, and tracker.py and each file got the same error

**Comment by kcg2015** [comment]
@maearnie, thanks for letting me know. So you have an error message even running helpers.py?

**Comment by SignalImageCV** [comment]
@kcg2015 , @maearnie, I think this error was related to python Object-Oriented Programming--the combination of class, and I have fixed this error. 
for example, in the main.py, "det = CarDetector()" should be written as "det = detector.CarDetector()", because it is outside the detector.py. 
in the helpers.py, "def draw_box_label(img, bbox_cv2, box_color=(0, 255, 255), show_label=True):" should be written as "def draw_box_label(self,img, bbox_cv2, box_color=(0, 255, 255), show_label=True):"

**Comment by kcg2015** [comment]
Thanks a lot, @SignalImageCV!  I will look into your suggestion and fix the bug.

**Comment by lad-admin** [comment]
@SignalImageCV  NameError: name 'draw_box_label' is not defined. I tried using your suggestion and it worked for CarDetector and did not work for draw_box_label. Is there a solved solution ? Thanks @kcg2015

**Comment by lad-admin** [comment]
Actually I solved it. You need to add helpers. draw_box_label in tracker.py and in main.py

**Comment by 3073** [comment]
This repo is very very nice and easy for beginners like me.  I would have given   multiple stars if it was possible. I understand most of the codes except the lines of codes from 122-162 in main.py 
it is better if anyone explain me.   thank you.
