### ISSUE TITLE
A question about video tracking

### ISSUE THREAD

**Issue by younghuvee** [kcg2015/Vehicle-Detection-and-Tracking#23]
Hi, thanks for your amazing project, i have a question about video tracking, how can i see the different ID for car in the final output video?

**Comment by kcg2015** [comment]
Sorry for the late reply,   you can modify the following function in the helper.py:
 draw_box_label(img, bbox_cv2, box_color=(0, 255, 255), show_label=True). 
Hope this helps.

**Comment by younghuvee** [comment]
> Sorry for the late reply, you can modify the following function in the helper.py:
> draw_box_label(img, bbox_cv2, box_color=(0, 255, 255), show_label=True).
> Hope this helps.

**Comment by younghuvee** [comment]
Hello，I mean that can I give the car an ID number to track it in the output video?

**Comment by kcg2015** [comment]
Yes.  Please see L148: tmp_trk.id = track_id_list.popleft() # assign an ID for the tracker.

**Comment by younghuvee** [comment]
Thank you, can i put 'ID' text on the detect rectangle just like this

```
text_x= 'x='+str((left+right)/2)
cv2.putText(img,text_x,(left,top-25), font, font_size, font_color, 1, cv2.LINE_AA)
text_y= 'y='+str((top+bottom)/2)
cv2.putText(img,text_y,(left,top-5), font, font_size, font_color, 1, cv2.LINE_AA)
```

**Comment by younghuvee** [comment]
@HWYangege   this my twitter address ,  looking forward your reply^_^

**Comment by kcg2015** [comment]
Of course. Feel free to make any changes as you see fit.

**Comment by kcg2015** [comment]
@younghuvee, let me close this issue for now.
