### ISSUE TITLE
Tracker without constant velocity

### ISSUE THREAD

**Issue by chokkarapu** [kcg2015/Vehicle-Detection-and-Tracking#25]
Dear Author(kcg2015),

your work is amazing and also great in sharing your work to research community.

Here you are considering the constant velocity model in the process matrix, as shown in snapshot:
![image](https://user-images.githubusercontent.com/3630515/69214374-d3811300-0b8c-11ea-8cf0-7200db60cef6.png)

Here Im having few queries mentioned below:
1) If ego vehicle is not moving in constant velocity and then how to deal for tracking the target objects?
2) what is DELTA_T, in your code mentioned a constant value =1. 

Iam able to track the object when I capture frames at 30FPS but unable to track the objects when frames are captured at 10FPS as my position is changing vsatly, so how to deal when frame rate is less around 10FPS?

Thanks for your valuable time, I eagery look forward for your response.

Thanks,
Anil.

**Comment by kcg2015** [comment]
@chokkarapu , thanks for the kind words!  To answer your questions:

1. You can consider a constant acceleration model. There are tons of tutorials on line, for example, https://vimeo.com/87854541. If should be very straight forward to integrate this model into the code.

2. Yes,  I set delta_t to 1. You can try different value, say delta_t = 2, to see if it works for low-frame-rate video, let me know. I am also curious.

Best,

Kyle

**Comment by kcg2015** [comment]
@chokkarapu, I figure that you have already figured out approaches with acceleration model and low frame rate. Let me close this issue for now.
