### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by klintan** [kcg2015/Vehicle-Detection-and-Tracking#29]
Hey, 
thank you for this awesome work! However I couldn't find any license information? Is it MIT- or BSD-licensed ?

**Comment by kcg2015** [comment]
Hi, @klintan,  this is still an on-going project, thought I have not been active recently. So I have not set the license up. Anyway, you can use it or modify it as you see fit.  Best, Kyle

**Comment by klintan** [comment]
Thanks!
