### ISSUE TITLE
low frame rate issue

### ISSUE THREAD

**Issue by ambakick** [kcg2015/Vehicle-Detection-and-Tracking#3]
For low frame rate the tracker is lagging, is there a way i can make it work for low frame videos.
Like for example changing the dt value in tracker.py

**Comment by kcg2015** [comment]
@ambakick,  you mean low frame rate videos? Could you provide an example?

**Comment by kcg2015** [comment]
@ambakick , what is the frame rate you are working on? I am very interested to know if you get it to work by adjusting the dt value in tracker.py?  Best, Kyle
