### ISSUE TITLE
About dealing with matched detections in main.py

### ISSUE THREAD

**Issue by YuPeize** [kcg2015/Vehicle-Detection-and-Tracking#4]
Whether an operation `tmp_trk.no_losses = 0` should be performed after the operation `tmp_trk.hits += 1` ?

**Comment by kcg2015** [comment]
Thanks a lot for bring this up. Let me double check and get back to you.

**Comment by kcg2015** [comment]
You are right. There is a possibility that tmp_trk.no_losses>0, then the same detection is matched again. Thus tmp_trk.no_losses needs to be reset to zero.  Thanks again for you spotting this bug!

**Comment by YuPeize** [comment]
Thanks for your approval！

**Comment by kcg2015** [comment]
Great. Let me close this issue for now.
