### ISSUE TITLE
Error: 'Tracker' object has no attribute 'R_ratio'

### ISSUE THREAD

**Issue by Biyu-GitHub** [kcg2015/Vehicle-Detection-and-Tracking#6]
Hello, this is an error when I run tracker.py.

File "tracker.py", line 58, in __init__
        self.R_diag_array = self.R_ratio * np.array

AttributeError: 'Tracker' object has no attribute 'R_ratio'

So, I want to know, where is 'R_ratio' defined?

Thank you!

**Comment by kcg2015** [comment]
@Biyu-GitHub, thanks for spotting this bug.  All self.R_ratio should be replaced with self.R_scaler. Let me know if you can run the code or  encounter other errors.

**Comment by by2026** [comment]
> @Biyu-GitHub, thanks for spotting this bug. All self.R_ratio should be replaced with self.R_scaler. Let me know if you can run the code or encounter other errors.

Thank you very much ! I can run the code now.

**Comment by Biyu-GitHub** [comment]
> @Biyu-GitHub, thanks for spotting this bug. All self.R_ratio should be replaced with self.R_scaler. Let me know if you can run the code or encounter other errors.
