### ISSUE TITLE
Tracker Error

### ISSUE THREAD

**Issue by MoustafaAyoub** [kcg2015/Vehicle-Detection-and-Tracking#8]
File "main.py", line 140, in pipeline
    tmp_trk = Tracker() # Create a new tracker
NameError: name 'Tracker' is not defined

I just ran your code as it is, but there is an error in the main.

**Comment by kcg2015** [comment]
@MoustafaAyoub,  see if  change  to tmp_trk = tracker.Tracker() works. Or change import tracker to from tracker import all.
Best.

**Comment by MoustafaAyoub** [comment]
Thank you, it worked.

**Comment by MoustafaAyoub** [comment]
Do you have any idea how can I make your program work on real time?

**Comment by kcg2015** [comment]
@MoustafaAyoub, cool. I have not looked into the detection in real time yet.  There are quite a few blogs/Githb repos on this subject. You can search object detection with webcam to get an idea.
Let me close this issue for the moment.
