### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by qiang92** [kcg2015/Vehicle-Detection-and-Tracking#9]
I think you should add "self.car_boxes = []" after "print('no detection!')" in file"detector.py" 124 line.
Otherwise it will keep showing the last position of previous object until the detector detects a new object.

**Comment by kcg2015** [comment]
Thanks for bring this up. Let me take a look and get back to you.

**Comment by kcg2015** [comment]
Thanks a lot for spotting this bug! I have already added this line of code (at line 125) in detector.py.

**Comment by kcg2015** [comment]
Let me close this issue for now.
